# Generated by Django 5.1.4 on 2024-12-26 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='productsimg/')),
                ('description', models.CharField(max_length=300)),
                ('size', models.CharField(choices=[('Small', 'Small'), ('Medium', 'Medium'), ('Large', 'Large')], max_length=6)),
                ('categories', models.CharField(choices=[('Mens', 'Mens'), ('Ladies', 'Ladies')], max_length=6)),
                ('currency', models.CharField(choices=[('$', 'USD'), ('रु', 'NRP')], max_length=3)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
