# Generated by Django 5.1.4 on 2024-12-26 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kapda', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcard',
            name='image_url',
            field=models.URLField(blank=True, help_text='Enter the URL of the image.', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='productcard',
            name='currency',
            field=models.CharField(choices=[('$', 'USD'), ('रु', 'NRP')], default='$', max_length=3),
        ),
        migrations.AlterField(
            model_name='productcard',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='productsimg/'),
        ),
    ]
