# Generated by Django 5.1.4 on 2024-12-26 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kapda', '0003_alter_productcard_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcard',
            name='size',
            field=models.CharField(choices=[('S', 'S'), ('M', 'M'), ('L', 'L')], max_length=6),
        ),
    ]
