# Generated by Django 5.1.4 on 2024-12-26 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kapda', '0005_alter_productcard_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcard',
            name='price',
            field=models.IntegerField(),
        ),
    ]
